### PR TITLE
[feature] add access_token support

### PR DESCRIPTION
**Pull request by wiquan**
## Overview
This simply adds support for [Personal Access Tokens](https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html) in Confluence.

## Dependencies
- https://github.com/justmiles/go-confluence/pull/2

### CODE REVIEW

**Comment by gemiware** [comment]
Please merge this! We want this for our corporate confluence...

**Comment by justmiles** [comment]
Could you confirm this isn't already supported?

**Comment by justmiles** [comment]
Ah, sorry just realized this is related to the bearer token. Will merge soon!

**Comment by justmiles** [comment]
All set https://github.com/justmiles/go-confluence/pull/2

**Comment by gemiware** [comment]
Miles, thanks for the swift action! Sorry to bother you again, but can we get a release containing this funcionality as well?

**Comment by justmiles** [comment]
all set [v3.4.0](https://github.com/justmiles/go-markdown2confluence/releases/tag/v3.4.0)

**Pull request merged**
