### PR TITLE
Use alpine image to make K8s ready

### PR DESCRIPTION
**Pull request by sscholl**
I can't use this tool, since it can not be deployed within a pod and being idle (e.g. sleep 10000).

### CODE REVIEW

**Comment by justmiles** [comment]
Hi @sscholl, I think there's a couple other options here we can leverage before introducing the alpine OS.

1. Deploy it as a [cronjob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/): This tool wasn't designed to be daemonized. Instead, it runs as a one-off workload to sync the files and exit. Rather than use `sleep` to pseudo daemonize it, deploy it as a cronjob.
2. Add new feature to run as a daemon: We can open up a new feature request to run the workload as a daemon. It would essentially `--watch` a directory for changes and sync them as they are made.

Option 2 needs to be developed, but you should be able to run with Option 1 now. Hope this helps!

**Comment by sscholl** [comment]
Hi @justmiles thanks for you reply. 
1. We need it in a CI pipeline. Unfortunally it is Jenkins and we use Jenkins K8s Agents to execute this command. When you do that, you can add containers - like markdown2confluence - and within the Pipeline we can execute shell commands within the container. To do that, it need to run permanentely.
2. This deamon would not be sufficient, since we retrieve the credentials within the Pipeline. But I need to set them during startup. At least as for now. However, a deamon is not what I want. 

What about a second tag with alpine?

Best regards
Simon

**Comment by justmiles** [comment]
I use this for my CI pipelines as well but with DroneCI. Although there's no shell, the build can still invoke the container's binary. Here's an example config for DroneCI:

```yaml
kind: pipeline
name: default

steps:
  - name: markdown2confluence
    image: justmiles/markdown2confluence:v3.3.1
    environment:
      CONFLUENCE_USERNAME:
        from_secret: confluence_username
      CONFLUENCE_PASSWORD:
        from_secret: confluence_password
    entrypoint:
      - /markdown2confluence
      - --endpoint
      - https://mysite.atlassian.net/wiki
      - --space
      - DEFAULT
      - /drone/src

```

It looks like this is supported in Jenkins. [Their docs](https://plugins.jenkins.io/kubernetes/#plugin-content-container-template) say that the `command` parameter will overwrite the entrypoint. I expect your template to look something like this:

```yaml
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: markdown2confluence
        image: justmiles/markdown2confluence:v3.3.1
        command: /markdown2confluence
        args:
          - --endpoint
          - https://mysite.atlassian.net/wiki
          - --space
          - DEFAULT
          - /drone/src
```

**Comment by sscholl** [comment]
@justmiles Thanks for your thoughts. Unfortunally, our Jenkins works differently. It starts the agent Pod with all tools and no workspace. Afterwards the GIT will be cloned. Then the upload step happens.
However I could try your approach by starting a later "stage" with this Pod.yaml. I hope Jenkins is OK with an empty stage. Also I wonder where the logs will end up.
... I will come back to you, once I find the time ...

**Pull request closed without merging**
